# Generated by Django 5.1.4 on 2025-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_merge_20230107_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewers2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reviews', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='pat',
        ),
        migrations.AddField(
            model_name='reviewers',
            name='reviews',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewers',
            name='time',
            field=models.DateTimeField(default='No review yet'),
            preserve_default=False,
        ),
    ]
